# Teams & GitHub usernames are in alphabetical order

Architecture: 
# Architecture
  - '@KevinGreene'

Audit & Accounting: 
# Claims & Accounting 
  - '@ana-rymorieva'
  - '@cynaria'
  - '@dandrade'
  - '@joelvazquez93'
  - '@mcortes95'
  - '@mspecter-kin'
  - '@mumoc'
  - '@nlipkind'
  - '@tenzaej'

Claims Team: 
# Claims Intake & Assignments + Claims Maintenance & Operations
  - '@aynurf'
  - '@carbroj'
  - '@DavisC0801'
  - '@Grady828'
  - '@JeannaNelson'
  - '@jelera'
  - '@kavita-alexa'
  - '@kkclark'
  - '@lizthrilla'
  - '@MandyWade0312'
  - '@milt3'
  - '@nancytn'
  - '@NathanJJPham'
  - '@nikkipolak'
  - '@rsdesoto'
  - '@rstockwe'
  - '@tgrux'
  - '@vickiticki'

Customer Acquisition & Retention:
# Ex-FL Aquisition & Retention + FL Aquisition & Retention
  - '@AlysonJansen'
  - '@AndrejsQA'
  - '@blai00'
  - '@boualom'
  - '@DragonQuills'
  - '@drench'
  - '@dvarelap'
  - '@gecugamo'
  - '@jasonswoj'
  - '@joseph-weber'
  - '@KellysIB'
  - '@nadiTsoyKin'
  - '@ndc-kin'
  - '@Pangelone'
  - '@peterbinks'
  - '@StevenZambito'
  - '@veragal'

Customer & UW Support:
# Customer Acquisition & Retention
  - '@bdivkin'
  - '@brittdri'
  - '@joegenglerkin'
  - '@kmcgrevey'
  - '@nadiTsoyKin'
  - '@tristinbaker'

Data Engineering:
# Data & Systems Engineering
  - '@AJB4'
  - '@benjaminmillunchick'
  - '@brettschwartz'
  - '@ElizaNikitina'
  - '@geddy8543'
  - '@gregloweatkin'
  - '@igalstr'
  - '@nvsgupta'

DevOps:
# Cloud Operations
  - '@cthomaspdx'
  - '@Mhart12'
  - '@natw'

Documents & Forms:
# Policy Platform
  - '@alfredorico'
  - '@celloward'
  - '@jckin'
  - '@mseankelly-Kin'
  - '@natalyaolshansky'
  - '@rueeazy'
  - '@thecalebmasters'
  - '@valeriabenetti'
  - '@victorclee'

Expansion:
# Policy Platform (Ex-FL Expansion)
  - '@baleighbi'
  - '@camposja'
  - '@Drewfergusson'
  - '@hebelken-kin'
  - '@Janat-kin'
  - '@sean-foley-kin'
  - '@utumno86'

Ratings:
# Policy Platform
  - '@cato-hga'
  - '@cvelasquez095'
  - '@dannyjle'
  - '@dubistdu'
  - '@itsbaska'
  - '@lidiayachnyk'
  - '@mariosaraiva'
  - '@pallavipanchavati123'

Prod Support:
# Cloud Operations
  - '@BrandonCzaja'
  - '@denbits'
  - '@edalvarezII'
  - '@jakefordycekin'
  - '@johnlonetree'
  - '@JonahHouseKin'
  - '@jonathandwang'
  - '@MattRice12'
  - '@nicofh'
  - '@sabrinagecu'

Release Management:
# Cloud Operations
  - '@brookeconnell'
  - '@jonathan-kline'

Security:
# Cloud Operations
  - '@Mlausche'
  - '@tlesec01'

Systems Engineering:
# Data & Systems Engineering
  - '@anegretekin'
  - '@jtantenucci'
  - '@mikefpardo'
  - '@scott-white-kin'
  - '@tnordloh'
