name: Team Label
on:
  workflow_call:
    inputs:
      configuration-path:
        required: true
        type: string
      teams-repo:
        required: true
        type: string
      teams-branch:
        required: true
        type: string
    secrets:
      CROSS_REPO_TOKEN:
        required: true
  pull_request_target:
    types: [opened]
permissions:
  contents: read
  pull-requests: write
jobs:
  team-label:
    runs-on: ubuntu-latest
    steps:
    - name: Team Labeler
      uses: JulienKode/team-labeler-action@v1.1.0
      with:
        repo-token: ${{ secrets.CROSS_REPO_TOKEN }}
        configuration-path: .github/teams.yml
        teams-repo: release-tools
        teams-branch: main
